---
- name: Playbook To Deploy nginx-ingress, Prometheus and Grafana
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Deploy nginx-ingress-controller 
    kubernetes.core.helm:
      name: nginx-ingress-controller
      chart_ref: oci://ghcr.io/nginx/charts/nginx-ingress
      release_namespace: default
      create_namespace: false
      chart_version: 2.0.1
      state: present

  - name: Add Prometheus chart repo
    kubernetes.core.helm_repository:
      name: prometheus-community
      repo_url: "https://prometheus-community.github.io/helm-charts"

  - name: Add Grafana chart repo
    kubernetes.core.helm_repository:
      name: grafana
      repo_url: "https://grafana.github.io/helm-charts"     

  - name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
    kubernetes.core.helm:
      name: prometheus
      chart_ref: prometheus-community/prometheus
      release_namespace: monitoring
      create_namespace: true
      state: present
      values:
        server:
          persistentVolume:
            enabled: false

  - name: Deploy latest version of Grafana chart inside monitoring namespace (and create it)
    kubernetes.core.helm:
      name: grafana
      chart_ref: grafana/grafana
      release_namespace: monitoring
      create_namespace: true
      state: present
      values:
        service:
          type: LoadBalancer